const fs = require('fs'), path = require('path')
const t = path.join(process.cwd(), 'src', 'app', 'feed', '[id]', 'page.tsx')
let c = fs.readFileSync(t, 'utf8')
c = c.replace(/\s*postTitle=\{[^}]+\}\n/, '\n')
fs.writeFileSync(t, c)
const v = fs.readFileSync(t, 'utf8')
const ctaIdx = v.indexOf('<FeedPostCTA')
const ctaEnd = v.indexOf('/>', ctaIdx)
console.log('CTA block:', v.slice(ctaIdx, ctaEnd + 2))
